import React from "react";
import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 20,
    backgroundColor: "#f3f3f3",
    justifyContent: "center",
    alignItems: "center",
  },
  card: {
    width: 300,
    padding: 15,
    borderRadius: 10,
    backgroundColor: "#fff",
    border: "1px solid #ccc",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
  },
  header: {
    textAlign: "center",
    marginBottom: 10,
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#444",
    textTransform: "capitalize",
  },
  separator: {
    borderBottom: "1px solid #ccc",
    marginBottom: 10,
  },
  details: {
    flexDirection: "row",
    marginBottom: 10,
  },
  textSection: {
    width: "70%",
    paddingRight: 10,
  },
  photoSection: {
    width: "30%",
    justifyContent: "center",
    alignItems: "center",
  },
  photo: {
    width: 70,
    height: 70,
    borderRadius: "50%",
    objectFit: "cover",
    border: "1px solid #ccc",
  },
  noPhoto: {
    width: 70,
    height: 70,
    borderRadius: "50%",
    border: "1px solid #ccc",
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
  },
  text: {
    fontSize: 10,
    marginBottom: 4,
  },
  textBold: {
    fontSize: 10,
    fontWeight: "bold",
  },
  additionalDetails: {
    marginTop: 10,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  footerText: {
    fontSize: 10,
  },
});

const VisitorPDF = ({ visitor }) => (
  <Document>
    <Page style={styles.page} size={"A4"} orientation="portrait">
      <View style={styles.card}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Visitor ID Card</Text>
        </View>

        <View style={styles.separator}></View>

        {/* Details Section */}
        <View style={styles.details}>
          {/* Visitor Info */}
          <View style={styles.textSection}>
            <Text style={styles.text}>
              <Text style={styles.textBold}>Name:</Text> {visitor.name}
            </Text>
            <Text style={styles.text}>
              <Text style={styles.textBold}>Gender:</Text> {visitor.gender}
            </Text>
            <Text style={styles.text}>
              <Text style={styles.textBold}>DOB:</Text> {visitor.date_of_birth}
            </Text>
          </View>

          {/* Photo */}
          <View style={styles.photoSection}>
            {visitor.photo ? (
              <Image
                style={styles.photo}
                src={`http://localhost:3000${visitor.photo}`} // Ensure the path to the photo is correct
              />
            ) : (
              <View style={styles.noPhoto}>
                <Text>No Photo</Text>
              </View>
            )}
          </View>
        </View>

        <View style={styles.separator}></View>

        {/* Additional Details */}
        <View style={styles.additionalDetails}>
          <Text style={styles.text}>
            <Text style={styles.textBold}>Visitor Date:</Text> {visitor.visiting_date}
          </Text>
          <Text style={styles.text}>
            <Text style={styles.textBold}>Whom to Meet:</Text> {visitor.whom_to_meet}
          </Text>
        </View>

        <View style={styles.separator}></View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Generated by Visitor Management System
          </Text>
          <Text style={styles.footerText}>{new Date().toLocaleDateString()}</Text>
        </View>
      </View>
    </Page>
  </Document>
);

export default VisitorPDF;
